### ISSUE TITLE
Project topic

### ISSUE THREAD

**Issue by patrickwang96** [patrickwang96/CS3343#1]
So...   

Any one got a suitable topic for this project? T T

**Comment by SherlockQiu** [comment]
What about an express management system?
It would contain five actors:
0/sender who can generate, send, trace the parcel, see the estimated delivery path and time and comment on postman
1/postoffice who maintains a map of branches a list of postman and is responsible to generate optimized delivery path among cities
2/branches who store and maintains the packages and announces sender and receivers the package is in such brunches.
3/postman who deliver parcels and check in them when they arrive in branches or receivers
4/receivers can receive and trace the parcel, see the estimated delivery path and time and comment on postman also they can change the delivery address

**Comment by wfz0755** [comment]
I think it's okay. Maybe we can talk about it further this weekend.

**Comment by lpzjerry** [comment]
The topic is perfectly fine if we could extend it into a project with the scale of close to the Library management system we have built since JUnit expects more interactions among modules. As far as I can see, there are only 4 classes included in the current version. Suppose we need more interactions among units within our system, what features can be included? Here are my thoughts:  <ul><li>The packages (Ext. pkg interface) can be assigned with different weights and each postman could carry a certain amount of packages. In such design, there would be interactions between postman and package.</li>
<li>The postoffice class can be decentralized by building a post office network to simulate the real-life delivery. The delivery process would then involve path planning, city-level package tracing etc.</li></ul>

 Other ideas are welcome.

**Comment by patrickwang96** [comment]
I personally think this idea is fine. This is a highly **modularized** project idea.    
However, I'm afraid that its architecture isn't complex enough @@ 

From my point of view, the interactions among modules are fairly simple.  

* Sender <-> Postoffice
* Office <-> branch
* Postman <-> Branch etc...

No offence, but I think current architecture of this proj idea is way too simple. I agree that this would be a great proj for modularized programming and test-driven software engineering though. 

Perhaps we may enhance this idea into a more complex project. Or maybe we just come up with a new idea.  ;-)

**Comment by SherlockQiu** [comment]
I think the project is extendable enough, e.g. to implement more real function

**Comment by patrickwang96** [comment]
From my point of view, a suitable project's architecture should be both highly customizable and modularized.   

_Take scrapy's design for example:_  

![scrapy_architecture](https://user-images.githubusercontent.com/26168657/30732075-60b263b2-9fa3-11e7-9398-bd2a152baf4d.png)

Your purposal and scrapy's design both are modularized. However, I think the express management system is somehow more difficult to extend.  Take scrapy as example, user can easily add plugins (middle wares) to extend the whole project to achieve various goals.  But express system's modules were strongly coupled together, which means modification cost is more.  

Anyway, I think this is not a major problem if we design express management properly.  So, I think this idea would be fine after a little adjustment.
